<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['greylisting_app_description'] = 'Приложение "Серый список" обеспечивает дополнительную защиту от спама и вирусов, отфильтровывая сообщения не соответствующие электронной почты.';
$lang['greylisting_app_name'] = 'Серый список';
$lang['greylisting_delay'] = 'Задержка';
$lang['greylisting_delay_invalid'] = 'Недопустимая задержка. ';
$lang['greylisting_maximum_retention_time_invalid'] = 'Максимальное время задержания - инвалид.';
$lang['greylisting_retention_time'] = 'Время хранения';
