<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['greylisting_app_description'] = 'The Greylisting app provides additional protection against spam and viruses by filtering out non-compliant e-mail messages.';
$lang['greylisting_app_name'] = 'Greylisting';
$lang['greylisting_delay'] = 'Delay';
$lang['greylisting_delay_invalid'] = 'Delay is invalid.';
$lang['greylisting_maximum_retention_time_invalid'] = 'Maximum retention time is invalid.';
$lang['greylisting_retention_time'] = 'Retention Time';
