<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['greylisting_app_description'] = 'Aplikacja szarych list dostarcza dodatkowej ochrony przez spamem i wirusami filtrując nietypowe wiadomości e-mail';
$lang['greylisting_app_name'] = 'Szare listy';
$lang['greylisting_delay'] = 'Opóźnienie';
$lang['greylisting_delay_invalid'] = 'Nieprawidłowa wartość opóźnienia.';
$lang['greylisting_maximum_retention_time_invalid'] = 'Maksymalny czas retencji jest nieprawidłowy.';
$lang['greylisting_retention_time'] = 'Czas retencji';
